services:
  php:
    container_name: farm-fusion-php
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ../farm-fusion-api:/var/www/html
    depends_on:
      - postgres

  nginx:
    container_name: farm-fusion-nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ../farm-fusion-api:/var/www/html
    depends_on:
      - php

  postgres:
    container_name: farm-fusion-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data:rw

  vue:
    container_name: farm-fusion-vue
    image: node:23-alpine
    working_dir: /app
    volumes:
      - ../farm-fusion-vue:/app
      # Optionally use a named volume to persist node_modules if needed
      - /app/node_modules
    ports:
      - "5173:5173" 
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - php

