
services:
  php:
    container_name: farm-fusion-php
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ../api:/var/www
    depends_on:
      - database

  nginx:
    container_name: farm-fusion-nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ../api:/var/www
    depends_on:
      - php

  database:
    container_name: farm-fusion-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
      POSTGRES_USER: app
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw

volumes:
  database_data:

